image:
  repository: debian
  tag: stable-slim

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 999

securityContext: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

secret:
  enabled: false
