ingress:
  host: chart-example.local
  annotations:
    kubernetes.io/ingress.class: nginx
ingresses:
  - host: chart-example.local
    tlsEnabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
  - host: another.local
    tlsEnabled: true
    annotations:
      kubernetes.io/ingress.class: nginx

gitRepository: github.com/laszlocph/demo-app
gitSha: xyz

vars:
  MY_VAR: "value"

volumes:
  - name: data
    path: /data
    size: 10Gi
    storageClass: default
