ingress:
  host: chart-example.local
  annotations:
    kubernetes.io/ingress.class: nginx
ingresses:
  - host: chart-example.local
    annotations:
      kubernetes.io/ingress.class: nginx
  - host: another.local
    annotations:
      kubernetes.io/ingress.class: nginx

gitRepository: github.com/laszlocph/demo-app
gitSha: xyz

vars:
  MY_VAR: "value"
