{{/* OneChart ingress snippet */}}
{{- define "onechart.ingress" }}
{{- $robustName := include "robustName" .root.Release.Name -}}
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  {{- if .longName }}
  name: {{ $robustName }}-{{ template "robustName" .ingress.host }}
  {{- else }}
  name: {{ $robustName }}
  {{- end }}
  namespace: {{ .root.Release.Namespace }}
  labels:
    {{- include "helm-chart.labels" .root | nindent 4 }}
  {{- if or (or .root.Values.gitSha .ingress.annotations) .root.Values.gitRepository }}
  annotations:
    {{- if .ingress.annotations }}
      {{- toYaml .ingress.annotations | nindent 4 }}
    {{- end }}
    {{- if .root.Values.gitSha }}
    gimlet.io/git-sha: {{ .root.Values.gitSha }}
    {{- end }}
    {{- if .root.Values.gitRepository }}
    gimlet.io/git-repository: {{ .root.Values.gitRepository }}
    {{- end }}
  {{- end }}
spec:
  {{- if default false .ingress.tlsEnabled }}
  tls:
    - hosts:
        - {{ template "robustName" .ingress.host | quote }}
      secretName: {{ printf "tls-%s" $robustName }}
  {{- end }}
  rules:
    - host: {{ template "robustName" .ingress.host | quote }}
      http:
        paths:
          - backend:
              serviceName: {{ $robustName }}
              servicePort: {{ .root.Values.containerPort }}
{{- end }}

{{- with .Values.ingress }}
  {{- template "onechart.ingress" (dict "root" $ "ingress" .) }}
{{- end }}

{{- range .Values.ingresses }}
{{template "onechart.ingress" (dict "root" $ "ingress" . "longName" true) }}
{{- end }}
