apiVersion: v1
kind: Service
metadata:
  name: {{ template "robustName" .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
spec:
  type: {{ if .Values.nodePortEnabled }}NodePort{{ else }}ClusterIP{{ end }}
  ports:
    {{- if not .Values.ports }}
    - port: {{ if .Values.svcPort }}{{ .Values.svcPort }}{{ else }}{{ .Values.containerPort }}{{ end }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if .Values.nodePort }}
      nodePort: {{ .Values.nodePort }}
      {{- end }}
    {{ else }}
    {{- range .Values.ports }}
    - name: {{ .name }}
      port: {{ if .svcPort }}{{ .svcPort }}{{ else }}{{ .containerPort }}{{ end }}
      {{- if .nodePort }}
      nodePort: {{ .nodePort }}
      {{- end }}
      targetPort: {{ .name }}
      protocol: TCP
    {{- end }}
    {{- end }}
  selector:
    {{- include "helm-chart.selectorLabels" . | nindent 4 }}
