{{- range .Values.namespaces }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .name }}
  annotations:
    {{- if .annotations }}
    {{- toYaml .annotations | nindent 4 }}
    {{- end }}
{{- end }}
