{{- range .Values.namespaces }}
{{- $budget := $.Values.budget }}
{{- if .budget }}
{{- $budget = .budget }}
{{- end }}
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ .name }}
spec:
  hard:
    limits.cpu: {{ $budget.cpu | mul $.Values.overcommit.cpu }}
    limits.memory: {{ $budget.memory | regexFind "[1-9]+" | mul $.Values.overcommit.memory }}{{ $budget.memory | regexFind "[a-zA-Z]+"  }}
    requests.cpu: {{ $budget.cpu }}
    requests.memory: {{ $budget.memory }}
    requests.storage: {{ $budget.storage }}
{{- end }}
