{{- range .Values.namespaces }}
{{- $budget := $.Values.namespace.budget }}
{{- if .namespace }}
{{- if .namespace.budget }}
{{- $budget = .namespace.budget }}
{{- end }}
{{- end }}
{{- $overcommit := $.Values.namespace.overcommit }}
{{- if .namespace }}
{{- if .namespace.overcommit }}
{{- $overcommit = .namespace.overcommit }}
{{- end }}
{{- end }}
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ .name }}
spec:
  hard:
    limits.cpu: {{ $budget.cpu | mul $overcommit.cpu }}
    limits.memory: {{ $budget.memory | regexFind "[1-9]+" | mul $overcommit.memory }}{{ $budget.memory | regexFind "[a-zA-Z]+"  }}
    requests.cpu: {{ $budget.cpu }}
    requests.memory: {{ $budget.memory }}
    requests.storage: {{ $budget.storage }}
{{- end }}
