image:
  repository: nginx
  tag: "latest"

replicas: 1

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 999

securityContext: {}

containerPort: 80

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

probe:
  enabled: false
  path: "/"

secret:
  enabled: false

shell: "/bin/sh"
