{{- range $key, $value := .Values.externalSecrets }}
{{- $secretStore := $value.secretStore | default dict }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $value.name | default (printf "%s-%d" $.Release.Name $key) }}
  namespace: {{ $.Release.Namespace }}
  labels:
spec:
  refreshInterval: {{ $value.refreshInterval | default "1h" }}

  secretStoreRef:
    name: {{ $secretStore.name | default "vault-backend" }}
    kind: {{ $secretStore.kind | default "SecretStore" }}

  target:
    name: {{ $value.target.name | default (printf "%s-%s" $.Release.Name $key) }}
    creationPolicy: {{ $value.target.creationPolicy | default "Owner" }}
    template:
      type: {{ $value.target.template.type | default "Opaque" }}
      engineVersion: v2
      data:
        {{- range $fileName, $fileContent := $value.target.template.data }}
        {{ $fileName }}: |
          {{- tpl $fileContent $ | nindent 10 }}
        {{- end }}

  data:
    {{- range $keydata, $valuedata := $value.data }}
    - secretKey: {{ $valuedata.secretKey }}
      remoteRef:
        key: {{ $valuedata.remoteRef.key }}
        property: {{ $valuedata.remoteRef.property }}
    {{- end }}
{{- end }}
